/**
 * COMPOSITION LAYER — the one module that knows both registries.
 * `lib/fields.ts`, `lib/sections.ts` and `lib/shells.ts` stay generic; joining a
 * shell to the sections it can render, and validating a whole site, happens here.
 */
import { SECTIONS } from '@/sections'

import { type ContentOf, buildSchema, f } from './fields'
import {
  type AnySection,
  type SectionInstance,
  createInstance,
  sectionsSchema,
} from './sections'
import { type Shell, supportedSectionIds } from './shells'

/** Site-wide settings, generated by the same form machinery as a section. */
export const SITE_CONTRACT = {
  musicUrl: f.text('URL musik (opsional)', {
    placeholder: 'https://…/lagu.mp3',
  }),
}

/** One client's site: which sections, in what order, with what content. */
export interface SiteContent extends ContentOf<typeof SITE_CONTRACT> {
  sections: SectionInstance[]
}

/**
 * A template is just a preset: a shell plus a default section order. The shell
 * decides how everything looks; the preset decides what's on the page to begin
 * with. Operators reorder, toggle, add and remove from there.
 */
export interface TemplatePreset {
  id: string
  name: string
  description: string
  shellId: string
  /** Section kinds, in order. Must all be renderable by the shell. */
  sections: string[]
  musicUrl?: string
}

/** The sections a shell can render — the add-section list, and the save whitelist. */
export function supportedSections(shell: Shell): AnySection[] {
  return supportedSectionIds(shell)
    .map((id) => SECTIONS[id])
    .filter(Boolean)
}

/** Scoped to what the shell can render, so an unrenderable section can't be saved. */
export function siteSchema(shell: Shell) {
  return buildSchema(SITE_CONTRACT).extend({
    sections: sectionsSchema(supportedSections(shell)),
  })
}

/**
 * Seed keys are derived from the preset, never `crypto.randomUUID()`: the editor
 * is a client component that Next also renders on the server, and keys end up in
 * rendered ids (`kupu-tab-${key}`) — random ones would differ between server and
 * client and break hydration. Sections *added* later get a uuid, which is safe
 * because that only ever happens from a click, in the browser.
 */
export function seedSite(preset: TemplatePreset): SiteContent {
  return {
    musicUrl: preset.musicUrl ?? '',
    sections: preset.sections.map((type, index) =>
      createInstance(SECTIONS[type], `${type}-${index}`)
    ),
  }
}
